### ISSUE TITLE
Trying to click on these titles results in a 500 error

### ISSUE THREAD

**Issue by hobojoe1848** [pybites/pbreadinglist#1]
*Edit, adding more books*

When I search for these specific titles and select them, I get a 500 error:

"Oh, The Places You'll Go!" - Dr Seuss.
Dreamworks Trolls (the book of the film)
Disney's the Lion Guard - Lost in the Outlands
https://pbreadinglist.herokuapp.com/books/JspbPwAACAAJ - Ahoy There, Little Polar Bear

**Comment by pybites** [comment]
@hobojoe1848 I cannot reproduce this, what were the conditions?

**Comment by hobojoe1848** [comment]
WTF, the problematic books no longer exist HAHA great way to solve the problem :P

Closing this as a non-issue now.
